### ISSUE TITLE
gulp build gives TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by GabLeRoux** [GabLeRoux/ansi-colors-chrome-extension#3]
```
gulp build
```
```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Liftoff.buildEnvironment (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:113:52)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:181:32)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:174:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:148:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:13:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by GabLeRoux** [comment]
Use [node-version-manager](https://github.com/creationix/nvm), use `7.2.0` (Works for me with this version)

```bash
nvm install v7.2.0
nvm use --delete-prefix v7.2.0
```
